### ISSUE TITLE
Fixed height, margins, padding, images, colors, align, more descriptive errors.

### ISSUE THREAD

**Issue by Draem** [PhoenixOnARoof/discordboats.club#38]
# Suggestion:
![](https://media.draem.me/q3Sq1DN.png)
**1** More descriptive error messages (I was not in the discord)

---

![](https://media.draem.me/m0im0DM.png)
**2** Fix the margins here.

---

![](https://media.draem.me/ipaoFR5.png)
**3** Align the chips, the username and the profile picture.

---

![](https://media.draem.me/FcW6M0J.png)
**4** Move this text here ;-;

---

![](https://media.draem.me/pNnHf7W.png)
**5** Make each bot card have a fixed height to prevent that ugly white space from collecting en messe.

---

![](https://media.draem.me/JHs3MFF.png)
**6** Invert the color for a more visible name.

---

![](https://media.draem.me/dJpJj9V.gif)
**7** Change the bot card colors when you switch from dark to white.

---

![](https://media.draem.me/9PbJvrr.png)
**8** Since discord profile pictures don't need to be high quality since they're so small, most images here will be low quality.

---

Most of these "issues" aren't bugs; they're suggestions i have to make things look better.
- [x] 1: Error Messages
- [x] 2: Margins
- [x] 3: Align
- [x] 4: Move text
- [ ] 5: Fixed height
- [ ] 6: Invert colors
- [ ] 7: Dark theme edit
- [ ] 8: Image quality

**Comment by jellz** [comment]
Thanks for making an issue.

**Comment by jellz** [comment]
@draeeeeeeeeeeeem How do you suggest we fix the last issue?

**Comment by Modelmat** [comment]
I'm assuming 8 would be fixed with the `?size=1024` parameter appended to the discord avatar url.

**Comment by PhoenixOnARoof** [comment]
@Modelmat dboats v1 is being left the way it is as we are working on v2. The follow-up to the first version that's supposed to be much better.
